apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Oi3oVA1EPucX/xykfNWcBhL1o7GGaA==,iv:PbjSkRxOcvfEk0LGMdP26kdU98FVcSkwtjPs2JWL9DQ=,tag:nLEd7zHYqGJH66U6DTUg5Q==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:BGubJ6b5A0o9qR3A6pQPg0+L4qTmWnfuXShAtP2NfbeDmGhOUg==,iv:iGvVtiprOiZhuELTz9WGwCnL7XyVG6vHWG+JEPKvfyk=,tag:uVM+AEKNsyi6tR4iRMRVYw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:D6PgYY4DgG4KDPn4s/tVJMw=,iv:ipJn2fXksVCYWTSnf91I40i5JAqLVGyfKHtBy22CoJY=,tag:XRz11qLkaTML9iHIMnsWfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12qlgg4qeyj582yjgny8aqflcug8kp5cy092he0azl3sjw5ffvg9qh0d50k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSk5qNlFmMWFEbDhkenYw
            NTIwUHhZNFAwMnd3OHVQQjFibTE4dnM4ZTNFCnJPSVcxdTF3WWhRM2ZUMjE4cllu
            RVkvc2tBVy9UaktXYitDeDB6U2RXOWsKLS0tIGhHcFoySENjYUVyd1Y0OEE2dWNO
            YVdoaHdGV2kxM0x1OCt4cUJLSElGMXcKik1R3txYgqANekmCAcRKBO0TU5/TvDfi
            YV1scixBPrsWLs/SxPdm0GCLVZIIre3F7mJhrBK+mGK6Kh1a/LFzKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-29T21:29:55Z"
    mac: ENC[AES256_GCM,data:dKLkRxPF4Ho1PpD/6Zqbkumekc0mx2EQzz/RfmIB/Sl7lMvnQY/6xS127W5HpcOW99aOST/foftMK1MdXBBGuXtMF+J289D2EvVZd0KWVXfXzHNFRT1FdkLPvx2lRnMl4wrNTEo4ewPsukOxAkrvhdIyK1Xa2NTx3xJt51auuRg=,iv:PLwnm0MAZDa9lviQXb9Hr6bPRtHwKyfhkY0s1gNfzI8=,tag:QDBW2AInjGOrp/bR2GgUxQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
