kind: ENC[AES256_GCM,data:eBMd4qQS,iv:oAhfk/vqjaqfjwqMjSazed2qwoGbRrAgb3Yng4bQxPM=,tag:RUjhMGyUVhm7c0C/jMbwkA==,type:str]
ansible_user: ENC[AES256_GCM,data:cLkf7byydQ==,iv:ARRMg9yzbRp14X5nRLpsZO8QUcVdXkv6JEfpIjY9C3M=,tag:rX93fY3ThtmX60h+zEdQ+g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:1nS8KEi2WblOn0Pi9SINtx+mXcx0mtYW,iv:g9xgYRk0yYJwHxC+xrUK2kveNynYGigl/Oz280AP3KQ=,tag:JgspLq6SqWbhUkqJnAUYSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12qlgg4qeyj582yjgny8aqflcug8kp5cy092he0azl3sjw5ffvg9qh0d50k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTTdQVmlSWmt1ckoxR3No
            enQzNnRLRUVYQnA4RmhMcVRGTW9ldmIvYUg4CkY4ZzFiV2I4N2hiU2NUSStjU25a
            Z2pUNncxdkF3V2ladWlyQ0FLZi9kNGMKLS0tIFA4eFdkcEYrb2hiSnpPaTRqZG1J
            WmNBcjBrQ3NYdmNmbis0NXF2OGkyRzQKFw3W9k+yFXakKLHBBi2H7LBqNpFYfBFY
            jygWD4PNZqkm53GN4vi/J+OGwwKm0ZIp3TCjP5UyU/gNMNDcaZgmyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-30T12:43:12Z"
    mac: ENC[AES256_GCM,data:yvfzoppq24BbFZW6jqvk+u7oncA09RgCZ4fYqLD9PIhVAc5VpNcWz99nSi3y1LVXoqdXqlhXXfBOOM5/FJrA/xWUiLHmc3YHZWfzZBOfG1HFbEQTWkgN0raPdsz0eBSOyL5+tcJG+fbsPHN3wuqoPpYvKLhfnY63LM8Sn2QViQ8=,iv:Pw62KgCLc8sEFJKDW7Le/BygafKBA4wo2WLbrj02LQM=,tag:3iyFxFEUL9DrEXHhE910Hw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
