kind: ENC[AES256_GCM,data:hjPgseaS,iv:u00anuzvQrswmB7dZLbwit25XtObxUddwGlRCukGd0Q=,tag:zTnA/xYlDlT62+ZsYd/RaA==,type:str]
ansible_user: ENC[AES256_GCM,data:dj6QCb02UQ==,iv:VUPLvGcw8zeE2ege/qCrI7Y3BDsE8R8leWUXrBBdIPY=,tag:VJeqSTzDsU3wA6+8G4sRyw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:5Gg+f26UngyrhhCdlBVHzwT9ODmYEPdX,iv:FuguPFH6Exx/vRYB9ZGLR5Gc3BH8940E+DC6qOswxzE=,tag:Alfn/Y6La5jwPiy35zbgyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12qlgg4qeyj582yjgny8aqflcug8kp5cy092he0azl3sjw5ffvg9qh0d50k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNUozMTVSY09xNTBOS2FE
            aUN1Y28vSW5IK2pUQ1JXTzJ5Uk5KdVBJSVNZCktqWGNvNGE2NWloTUhMK0NncWNZ
            RndiRGxnc000UTh3WUlaamhWKzF2VjQKLS0tIDlldm42RStSMUl2OHcvZ25XVko1
            Njh2OE1UWFBMOEg5L05vSjBpRTE1T1EK4enxbaVmUk7lORotqvEp+FdBB635UYlg
            kwifN/1d4A72qqt03pl0KMubVfoQHibwhzdZ3YmN17zZt7VAMxVZMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-29T21:29:55Z"
    mac: ENC[AES256_GCM,data:vEr3nIz+d/mowGoawpOLjXzM3Mzxx+2wGrlM9W7DW5sUoN+1NiqSnUM6vqkOwlxV3l8ZzfajrWLuAZhBbR9CAlpK7ZqgMwBsjrpnJd4B369TKzQ8EAKVFXGGyS77BpR+nc5NgCTekSeIWrokx0vv/FpVZgdM+TrHWI/oK5/tmpk=,iv:XN5lb83SwdPJx29EhglBdErWMvgMu6OEWA4hzOgWFQw=,tag:vXNm5rFpBsz74h3F8pytAQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
