apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:/qBPz9Mm8iEWBzJVunkz6VG4rpjg,iv:/e6wEBAKnSDq2zzUX8bVoN28k1ALSImswmlv6qiO4BI=,tag:LymqMeLw+tmpOwXo9in4Pw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12qlgg4qeyj582yjgny8aqflcug8kp5cy092he0azl3sjw5ffvg9qh0d50k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SzJXK21xamt1dk12UUZm
            dXp0K2c0U0Q2TjJPaUpvM0xjRTZtWlVrYmtRCmlyWGFpUUtGMCs4VHBJUWtiTGwv
            OElGdFQ0UlpwczRjZktGTE5QZHhBbjQKLS0tIGN2YzhiVHRzWEtNSVVMdDVUY0Z2
            T29OaFUwQ2p0Z0ZYUm9rY1FndE40YmcKZW3aiqjHDkXHarLjLHRwQbK7RQ0f0Vce
            oUtarRsrZ0aG/wYWEOa3m94WNuAV58TGnYQfHSwMT/g2TKYj8uA/cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-29T21:29:55Z"
    mac: ENC[AES256_GCM,data:q6VmK7OXqku2cDbQHWi2vXpH7wn7ONj4yTtgk50Shcg2N6tcj4eAASmXyp1FMT+s0rL+HXM1dJgC2xd8APt99YCuz1itZM6yGFvhFOPWhUj6RCNotaGqJWvzqsRRezkdXSRIjSdfxFturoR9hOxQGTU/+wyJX0AY+nOHfQ5wEZQ=,iv:ZDJtumtR7EmMTHNzEeXSc//KdTK06ArjwV/s+mNDKfA=,tag:J5neEzOXGF5wn5HdBUlH2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
