apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:9mYufDzWViMU3vSZEHUTdOP0gwQz,iv:2H2j038L8X06KeZntcfKzhe9aY4CjnMDqwLf9nop0Ns=,tag:dm8A0iaFcpxrNhHuHMjp0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12qlgg4qeyj582yjgny8aqflcug8kp5cy092he0azl3sjw5ffvg9qh0d50k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RDBTcDRJUXNZS3A0NVZx
            a212VGNOUG1Rb2k3RXVmTzhZejZsWUc0SG04CkhMMDJuSEoxMXc2VUk4UjNqZmpW
            YUl0ZXpCVW1rVHJ6ZURFYTFzV3ZkRnMKLS0tIGczcUxET3loUkdJbmhORllkOUFB
            LzNvZ3BwODlUdkQxYlZRRG4rUkdFNFkKZkoeVQ6qY9Ai5FskmXCWM6rUWQ+Hj5wl
            U2+MrQGYuZlagGTYY/zU3fFUjvsyEEQH0Iclfaz8gTvEvc0S6NRRZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-29T16:16:02Z"
    mac: ENC[AES256_GCM,data:lKotX8GN/Eil4a9N0EQ2AAi26KQCVsqJDRj2LajjyV3HI33xCyRk2m5UnkJhh60m3dz2mYh3YuGKGr28T2XdUyXylkb/xhN0KnWb9T2j2K4oz2a1++eoeE7OFUTPO1atOHZ0b6lufEXZfWvN3VcMEtGa38FRNbMdX6l/DuqohzU=,iv:VFiPCBzUFXskSmuCJ5IR2Z+p7YvtUnikK1zdp4MdPEo=,tag:09UkEvYNaTA231qJaLK/Xg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
