apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:ephljpvnRWv9uP6kXxEccsRWMc5eUv5T3eCvosFr0Iub36Dv80ahICTE+3XzCZ9usGlqja29XdNUHo6H,iv:/rRY/Q92JiSE/kXqlQyHUg+o0FrxMpxlM0zTRL9o1AE=,tag:/B1PVml3kvVqLw4iOCIJgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12qlgg4qeyj582yjgny8aqflcug8kp5cy092he0azl3sjw5ffvg9qh0d50k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSHZ1NDhhbnpiYkk1aGpr
            WXdabzk1Sk9SQW05Yzc4YnVJek9KSE9qRVZNClovZ3A1QTlmeHU1cCsxaVVDNmh4
            NjZDOU5Tb0NwNVE3NzBMVDBLcVY1bDgKLS0tIG1sSi8zZUFPbmFjdmsvcTZXSWgv
            akx6VFZRRDF3bFovcVpIaHNZZTN5ZE0KAmgtnyfzGFtCTK4vElkN/ubuiZ1cS5gw
            DLWcKSf4oKqeAIrK1CaqHTc+Pgw5pJ8tKPjVgHIauYC/jyc7NyhZ0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-29T21:29:58Z"
    mac: ENC[AES256_GCM,data:53BcGMByEKY7K/6PIZViasbaGuxFD5DQY/i/6xMnxDxITfqJ/icyjTmAQAVc36DOGm+iyQ1TJzFDcb2svl5IDtZRPbN0SeIIL8OnW7fO2w8q8N1iE1V9+h7U1ZE9b6mt0xAQt7HgB1pxUyb78nyft3eu2mWyqmuhUUX8/qEtDk4=,iv:ZI9QNjXK3WKmqowkN7qpzVL0Ka2/9HlHrCIiIKd8eNI=,tag:ejMj1yhV3zV4J+iRmCdLyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
