apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:zKa3gCJG1nQ2j+ob,iv:pNrlZ0uN75hnbjhdiPxi2oj7crb7Z6rJBfdOjoXKGWM=,tag:ouzutYF9YZY5FkeyawLKuA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:PCRRPoNBYXPBBxwxpTX6rgpwx7CVWQ==,iv:6UNF7gLEWjYABaI1gQGIvRy21S/EWZsNbStkOtHwO9g=,tag:y1qHrRf5gPQBkryIyvNliQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12qlgg4qeyj582yjgny8aqflcug8kp5cy092he0azl3sjw5ffvg9qh0d50k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUVVSSUxweWRGc0YvSFdR
            SFR0a3NaR05henJadEpzcE5wekxNZ2U2a3lrCk1GV2hYdHk5aXRUL2lGS2VxMHc1
            RnVBY2NHRDZnQTJNT3k1Vis3ay84N3MKLS0tIE9obUNSZkxNeTRiTjJUcWJhbDJB
            R0lORVBEc1BNRy90YjhvZ2xGZ0krWDgKIhhX8CmCLW1sTK0Y058WdHE5lM8YUtam
            KnsVkPk1+eHXB1tF10w1Vy9NWcsYeRaznuVmkju+UPzTiEK7qW35qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-29T21:29:55Z"
    mac: ENC[AES256_GCM,data:RlotBp0Y3jarKjb5n2IuuoSnES6ydwz5HaYlhUUC/jBKA7A2CaTEMXo0S5Sp1eLOhzRzKraJ47teP0RTTv3m7U02yng99Fj7Nhbtj6r86rvlF3YmrvoxMDxWsAmj/RRCJxOVNBNeSKw1y9wEreR5FiQjNDsTMbZtRDDdcgyM5WY=,iv:linMzvHu9+cQXaEXB8pnph/5Oicd7lbxvdERls+Siqo=,tag:jUw6yIOrlhEdYFBP4Hbs7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
