---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/New_York"
  KUBE_VIP_ADDR: "10.100.155.254"
  METALLB_LB_RANGE: "10.100.155.220-10.100.155.230"
  METALLB_K8S_GATEWAY_ADDR: "10.100.155.220"
  METALLB_INGRESS_ADDR: "10.100.155.221"
