apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:TfqE0JXh1Kj6fDmd,iv:bXPHycamGToWvVGJtDgqTzbc0W/45Z6sVI3TyQP2BBY=,tag:OwysiVqFG2n5FFV317RF0A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:6cxIWIhoV04uZY1tgUvTLdA7ApL8rQ==,iv:vEtivKAfM8NxdkerO0tHJrWvAWPfT2WwZZyTfotYcfQ=,tag:AXkDlF65Pvv6VEzQ+V67jQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12qlgg4qeyj582yjgny8aqflcug8kp5cy092he0azl3sjw5ffvg9qh0d50k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaGVwdnFGM1Z3NHl1VXlm
            KzRlWGVKVWthUVJIVmNOSkVDZGtiREgrU3lzCnYvRUIyWUxVc0lhVVp1N2FNYVl1
            WFBkczREZ2RZd0dqT3RvdnV2cVQ5dXcKLS0tIDhGZ2J1VHV5MndMWXRnRnFUR01C
            blo5ZjY4b3E2a1AwcG9ZSUVRRGpZM3cKxczWi1kV16MZDYIrBUS0MbtwiLL0jTW/
            8YdZNXYzMaqbpBKMknzmRVw28AhrYvV3GomMUzN1dGn9MLuzmaLmtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-30T12:43:11Z"
    mac: ENC[AES256_GCM,data:hBbxBSdT0jepXVs8kc0GkVVanIIBldDFHa27AW1IlkmCnaOBYQNCm0Y+0mZrLr9z3OUuHEE5MaIGq3lf6kwZZa7c9bSE7dWs3mohKMQNMNkUCFHH+Y/w2Y5cPzqU3uadOOzXhjDEAcdp6s6nP7S69Ic6CqcMnzd55TjyG6phNQ8=,iv:V3n8ltBsLV489ApaVaFCb/zDNH0ZSYdIrH4VwDcmW7U=,tag:hRhS7ktE/1Z+8mq5OLP7rw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
